#ifndef MINIBOX_WSD_H
#define MINIBOX_WSD_H
#include <stddef.h>

enum mb_wsd_kind { MB_WSD_NONE=0, MB_WSD_PROBE=1, MB_WSD_RESOLVE=2 };
struct mb_wsd_request {
    enum mb_wsd_kind kind;
    char message_id[192];
    char types[256];
    char endpoint[192];
};

int mb_wsd_parse(const char *xml,size_t len,struct mb_wsd_request *out);
int mb_wsd_is_print_probe(const struct mb_wsd_request *r);
int mb_wsd_is_scan_probe(const struct mb_wsd_request *r);
int mb_wsd_is_device_probe(const struct mb_wsd_request *r);
int mb_wsd_probe_supported(const struct mb_wsd_request *r);

/*
 * Build one WS-Discovery ProbeMatches/ResolveMatches response.
 * endpoint must be a stable urn:uuid:... identity.
 * xaddr is the HTTP metadata-exchange endpoint advertised to Windows.
 * response_message_id must be a urn:uuid:... generated by the caller.
 * Returns response byte length, 0 when the request does not match this
 * device, or a negative value on invalid/truncated input.
 */
int mb_wsd_build_match(const struct mb_wsd_request *r,
                       const char *endpoint,
                       const char *xaddr,
                       const char *response_message_id,
                       unsigned long instance_id,
                       unsigned long message_number,
                       char *out,size_t cap);

#endif
